---
web-dev:
  hosts:
    host1:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: ivan

#  db-dev:
#    hosts:
#      host2:
#        ansible_host: localhost
#        ansible_port: 22
#        ansible_user: ivan

all:
  children:
    web-dev:
    #  db-dev:
