---
nginx_remove_default_vhost: "true"
nginx_vhosts:
  - listen: "8080 default_server"
    server_name: _
    root: "/var/www/html"
    index: "index.html index.htm index.nginx-debian.html"
    extra_parameters: |
      location / {
        try_files $uri $uri/ =404;
      }
